FROM mcr.microsoft.com/vscode/devcontainers/javascript:0-14

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get -y install git

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get -y install <your-package-list-here>

# [Optional] Uncomment this line to install global node packages.
# RUN su vscode -c "npm install -g <your-package-list-here>"